"""Added sponsors

Revision ID: 618145eaffba
Revises: b71b6f135a19
Create Date: 2025-01-21 12:44:44.856645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618145eaffba'
down_revision: Union[str, None] = 'b71b6f135a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('sponsors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'sponsors')
    # ### end Alembic commands ###
