"""Removed sponsors

Revision ID: 620b16969571
Revises: 618145eaffba
Create Date: 2025-01-21 12:45:43.485965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620b16969571'
down_revision: Union[str, None] = '618145eaffba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'sponsors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('sponsors', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
